base branch with API v.0.7 usage, put migrations into startup script
uploadcare/pyuploadcare-example pull request #19
Opened 2022-11-28 17:32 UTC by ivanredbread

## Description

base branch with API v.0.7 usage, put migrations into startup script

- [x] merge [changes in library](https://github.com/uploadcare/pyuploadcare/pull/222)
- [x] switch `pyuploadcare` dependency to `rev = "main"` before merging into `main` here

## Checklist

- [ ] Tests (if applicable)
- [x] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-12-13 16:05 UTC, rsedykh requested changes

2022-12-13 16:05 UTC, rsedykh commented on README.md
> +- labels recognition
```suggestion
- object recognition
```

2022-12-13 16:05 UTC, rsedykh commented on README.md
> +#### Labels recognition via AWS
```suggestion
#### Object recognition via AWS
```

2022-12-13 16:07 UTC, rsedykh requested changes

2022-12-13 16:07 UTC, rsedykh commented on README.md
> +Use can execute operations that wrapped as addons.
```suggestion
User can execute operations that wrapped as addons.
```

Or you wanted to use "You"?

2022-12-26 03:52 UTC, rsedykh approved these changes
It would be lovely to avoid non en localization in screenshots. E.g. img/file_upload.png for choose file.

2022-12-26 10:11 UTC, ivanredbread commented
Feel free to rewrite this file with correct one if your system locale provides an opportunity to make screenshot with preferable langauge!

2022-12-26 11:30 UTC, merged